---
abstract: 'Load your schema definition from a DBMS'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Fey::Test: 0.07
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fey-Loader
requires:
  DBI: 0
  Fey: 0
  Moose: 0
  MooseX::Params::Validate: 0.08
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey-Loader
  repository: http://hg.urth.org/hg/Fey-Loader
version: 0.12
